# Generated by Django 2.1 on 2019-04-12 12:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('photo', models.BinaryField(blank=True, null=True)),
                ('introduction', models.TextField(null=True)),
            ],
            options={
                'db_table': 'actor',
            },
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100, unique=True)),
                ('foreign_title', models.CharField(max_length=128, null=True)),
                ('director', models.CharField(max_length=100)),
                ('catagory', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=255)),
                ('releasetime', models.CharField(max_length=50)),
                ('poster', models.ImageField(blank=True, upload_to='')),
                ('description', models.TextField()),
            ],
            options={
                'db_table': 'movie',
            },
        ),
        migrations.CreateModel(
            name='MovieActor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor_id', models.ForeignKey(db_column='actor_id', on_delete=django.db.models.deletion.CASCADE, to='base.Actor')),
                ('movie_id', models.ForeignKey(db_column='movie_id', on_delete=django.db.models.deletion.CASCADE, to='base.Movie')),
            ],
            options={
                'db_table': 'movie_actor',
            },
        ),
        migrations.AlterUniqueTogether(
            name='movieactor',
            unique_together={('movie_id', 'actor_id')},
        ),
    ]
