# Generated by Django 2.1 on 2019-04-15 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('flight_number', models.CharField(max_length=10, unique=True)),
                ('departure', models.CharField(max_length=100)),
                ('destination', models.CharField(max_length=100)),
                ('check_in_time', models.DateTimeField(max_length=50)),
                ('check_out_time', models.DateTimeField(max_length=50)),
                ('price', models.PositiveIntegerField()),
            ],
            options={
                'db_table': 'flight',
            },
        ),
        migrations.CreateModel(
            name='People',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('id_number', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'people',
            },
        ),
    ]
