# Generated by Django 2.1.5 on 2019-04-13 12:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='flights',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flightid', models.CharField(max_length=100)),
                ('starttime', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date published')),
                ('endtime', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date published')),
                ('price', models.FloatField()),
                ('startplace', models.CharField(max_length=255)),
                ('endplace', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'flights',
            },
        ),
    ]
