# Generated by Django 2.1.5 on 2019-04-14 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flight', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flights',
            name='endtime',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='flights',
            name='starttime',
            field=models.CharField(max_length=100),
        ),
    ]
