# Generated by Django 2.1 on 2019-04-15 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flight', '0002_auto_20190414_1120'),
    ]

    operations = [
        migrations.AddField(
            model_name='flights',
            name='volume',
            field=models.IntegerField(default=1000),
        ),
    ]
