# Generated by Django 2.1 on 2019-04-15 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flight', '0003_flights_volume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flights',
            name='endtime',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='flights',
            name='starttime',
            field=models.DateTimeField(),
        ),
    ]
