# Generated by Django 2.1 on 2019-04-13 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_user_identity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='identity',
            field=models.CharField(default='tourist', max_length=15),
        ),
    ]
